from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    replaces = [
        ('production', '0001_initial'),
        ('production', '0002_customer_payment_status_labels'),
    ]
    dependencies = [("core", "0001_baseline"), ("inventory", "0001_baseline"), ("procurement", "0001_baseline"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='ProductionRequest', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('requested_by', models.CharField(help_text='e.g. Main Store', max_length=120)), ('qty', models.DecimalField(decimal_places=2, max_digits=12)), ('needed_by', models.DateField(blank=True, null=True)), ('notes', models.TextField(blank=True)), ('status', models.CharField(choices=[('pending', 'Pending'), ('in_production', 'In production'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=15)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.finishedgood'))], options={'ordering': ['-date', '-id']}),
        migrations.CreateModel(name='ProductionOrder', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('order_type', models.CharField(choices=[('internal', 'Internal'), ('customer', 'Customer')], default='internal', max_length=10)), ('customer_name', models.CharField(blank=True, max_length=120)), ('qty', models.DecimalField(decimal_places=2, max_digits=12)), ('notes', models.TextField(blank=True)), ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=10)), ('completed_date', models.DateField(blank=True, null=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.finishedgood')), ('linked_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionrequest'))], options={'ordering': ['-date', '-id']}),
        migrations.AddField(model_name='productionorder', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='productionrequest', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='productionorder', name='qty', field=models.DecimalField(decimal_places=2, help_text='In individual units — production is automatically rounded up to whole batches.', max_digits=12)),
        migrations.AlterField(model_name='productionrequest', name='requested_by', field=models.CharField(blank=True, help_text='e.g. Main Store', max_length=120)),
        migrations.RemoveField(model_name='productionrequest', name='business'),
        migrations.RemoveField(model_name='productionrequest', name='created_by'),
        migrations.RemoveField(model_name='productionrequest', name='finished_good'),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('order_type', models.CharField(choices=[('customer', 'Customer order'), ('physical_store', 'Physical store order')], default='physical_store', max_length=15)), ('customer_name', models.CharField(blank=True, help_text='Required for a customer order; leave blank for a physical store restock.', max_length=120)), ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Cash', help_text='Only relevant for customer orders — recorded on the Sale created when this completes.', max_length=10)), ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10)), ('notes', models.TextField(blank=True)), ('approved_date', models.DateField(blank=True, null=True)), ('completed_date', models.DateField(blank=True, null=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-date', '-id']}),
        migrations.CreateModel(name='OrderItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('batch_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('piece_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)), ('price', models.DecimalField(decimal_places=2, default=0, help_text="Snapshot of the product's selling price at order time — set automatically.", max_digits=12)), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.finishedgood')), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.order'))], options={'abstract': False}),
        migrations.DeleteModel(name='ProductionOrder'),
        migrations.DeleteModel(name='ProductionRequest'),
        migrations.AlterField(model_name='order', name='order_type', field=models.CharField(choices=[('customer', 'Customer Order'), ('physical_store', 'Physical Store Order')], default='physical_store', max_length=15)),
        migrations.AlterField(model_name='order', name='order_type', field=models.CharField(choices=[('distribution', 'Distribution Order'), ('online', 'Online Order'), ('physical_store', 'Physical Store Order')], default='physical_store', max_length=15)),
        migrations.AddField(model_name='order', name='customer_region', field=models.CharField(blank=True, help_text='Optional reporting region/territory for distribution or online customer analytics.', max_length=100)),
        migrations.AddField(model_name='order', name='customer_group', field=models.CharField(blank=True, help_text='Optional customer group/segment for distribution or online customer analytics.', max_length=100)),
        migrations.AlterField(model_name='order', name='customer_name', field=models.CharField(blank=True, help_text='Required for distribution and online orders; leave blank for a physical store restock.', max_length=120)),
        migrations.AlterField(model_name='order', name='payment_method', field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Cash', help_text='Relevant for distribution/online orders — recorded on the Sale created when this completes.', max_length=10)),
        migrations.CreateModel(name='ProductionCostSnapshot', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('production_date', models.DateField()), ('produced_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)), ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16)), ('cost_source', models.CharField(default='latest_procurement', max_length=20)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cost_snapshots', to='inventory.finishedgood')), ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='production.order')), ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='production.orderitem'))], options={'ordering': ['-production_date', '-id']}),
        migrations.CreateModel(name='ProductionCostLine', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)), ('usage_unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16)), ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)), ('source', models.CharField(default='latest_procurement', max_length=20)), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial')), ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productioncostsnapshot'))]),
        migrations.AlterField(model_name='productioncostline', name='source', field=models.CharField(default='latest_procurement', max_length=20)),
        migrations.AlterField(model_name='productioncostsnapshot', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='productioncostsnapshot', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='productioncostsnapshot', name='cost_source', field=models.CharField(default='latest_procurement', max_length=20)),
        migrations.AddField(model_name='order', name='transaction_type', field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=10)),
        migrations.AddField(model_name='order', name='unpaid_description', field=models.CharField(blank=True, default='', help_text='Required when this physical-store order is unpaid.', max_length=255)),
        migrations.AddField(model_name='productioncostsnapshot', name='batch_number', field=models.CharField(blank=True, default='', max_length=40)),
        migrations.AddField(model_name='productioncostsnapshot', name='expiry_date', field=models.DateField(blank=True, null=True)),
        migrations.AlterField(model_name='productioncostsnapshot', name='cost_source', field=models.CharField(default='latest_procurement', max_length=40)),
        migrations.AddField(model_name='order', name='account', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='core.cashaccount')),
        migrations.AlterField(model_name='order', name='transaction_type', field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid')], default='paid', help_text='Used only for Physical Store orders; customer orders are receivables until paid through Finance.', max_length=10)),
        migrations.AlterField(model_name='order', name='transaction_type', field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', help_text='Physical Store purpose only: paid stock restock or non-cash product issue.', max_length=10)),
        migrations.AddField(model_name='order', name='customer_payment_status', field=models.CharField(choices=[('paid', 'Paid at request'), ('unpaid', 'Pay later')], default='paid', help_text='Distribution/Online only: whether the customer paid at request time or will pay later.', max_length=10)),
        migrations.AddField(model_name='order', name='customer_payment_method', field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Transfer', max_length=10)),
        migrations.AddField(model_name='order', name='customer_payment_account', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_payments', to='core.cashaccount')),
        migrations.AlterField(model_name='order', name='customer_payment_status', field=models.CharField(choices=[('paid', 'Received'), ('unpaid', 'Receivable')], default='paid', help_text='Distribution/Online only: whether the customer payment has been received or remains a receivable.', max_length=10)),
    ]
