from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def link_order_customers(apps, schema_editor):
    Customer = apps.get_model('sales', 'Customer')
    Order = apps.get_model('production', 'Order')
    for order in Order.objects.exclude(customer_name=''):
        name = (order.customer_name or '').strip()
        if not name:
            continue
        customer, _ = Customer.objects.get_or_create(business_id=order.business_id, name=name, defaults={'created_by_id': order.created_by_id, 'active': True, 'region': order.customer_region or '', 'customer_group': order.customer_group or ''})
        if order.customer_id is None:
            order.customer_id = customer.pk
            order.save(update_fields=['customer'])

class Migration(migrations.Migration):
    replaces = [
        ('production', '0003_production_batches_customer_links'),
        ('production', '0004_shortage_reconciliation'),
        ('production', '0005_production_destination'),
        ('production', '0006_non_stock_purpose'),
        ('production', '0007_order_material_usage'),
        ('production', '0008_alter_order_customer_payment_method_and_more'),
        ('production', '0009_productionbatch_excess_allocation'),
        ('production', '0010_orderitem_production_plan'),
    ]
    dependencies = [("production", "0001_foundation"), ("sales", "0001_foundation"), ("inventory", "0001_baseline"), ("core", "0001_baseline"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AddField(model_name='order', name='customer', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='sales.customer')),
        migrations.CreateModel(name='ProductionBatch', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('production_date', models.DateField()), ('batch_number', models.CharField(max_length=60)), ('expiry_date', models.DateField(blank=True, null=True)), ('planned_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('produced_units', models.DecimalField(decimal_places=2, default=0, help_text='Gross units produced before wastage/rejection.', max_digits=14)), ('wastage_units', models.DecimalField(decimal_places=2, default=0, help_text='Units lost, rejected or otherwise not saleable.', max_digits=14)), ('wastage_reason', models.CharField(blank=True, default='', max_length=255)), ('notes', models.TextField(blank=True, default='')), ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=16)), ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_productionbatch_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_productionbatch_created', to=settings.AUTH_USER_MODEL)), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='inventory.finishedgood')), ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='production.order')), ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='production.orderitem'))], options={'ordering': ['-production_date', '-id']}),
        migrations.AddConstraint(model_name='productionbatch', constraint=models.UniqueConstraint(fields=('business', 'batch_number'), name='unique_production_batch_per_business')),
        migrations.CreateModel(name='ProductionQualityCheck', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('status', models.CharField(choices=[('pending', 'Pending inspection'), ('passed', 'Passed'), ('conditional', 'Passed with conditions'), ('failed', 'Failed')], default='pending', max_length=12)), ('checked_at', models.DateTimeField(blank=True, null=True)), ('notes', models.TextField(blank=True, default='')), ('defects', models.TextField(blank=True, default='')), ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='production.productionbatch')), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_productionqualitycheck_set', to='core.business')), ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_quality_checks', to=settings.AUTH_USER_MODEL)), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_productionqualitycheck_created', to=settings.AUTH_USER_MODEL))], options={'ordering': ['-checked_at', '-id']}),
        migrations.AddField(model_name='productioncostsnapshot', name='production_batch', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='production.productionbatch')),
        migrations.RunPython(link_order_customers, migrations.RunPython.noop),
        migrations.AlterField(model_name='order', name='transaction_type', field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', help_text='Earlier physical-store order payment field; direct sales are recorded in Sales.', max_length=10)),
        migrations.AlterField(model_name='order', name='customer_payment_method', field=models.CharField(blank=True, default='Transfer', max_length=10)),
        migrations.AlterField(model_name='order', name='unpaid_description', field=models.CharField(blank=True, default='', max_length=255)),
        migrations.AlterField(model_name='order', name='payment_method', field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Cash', help_text='Earlier customer-order payment field; current customer payments are handled through Finance.', max_length=10)),
        migrations.AddField(model_name='productionbatch', name='shortage_flag', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='productionbatch', name='shortage_reason', field=models.CharField(blank=True, default='', max_length=255)),
        migrations.CreateModel(name='ProductionBatchReconciliation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('quantity', models.DecimalField(decimal_places=2, max_digits=14)), ('reason', models.CharField(max_length=255)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_productionbatchreconciliation_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_productionbatchreconciliation_created', to=settings.AUTH_USER_MODEL)), ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_out', to='production.productionbatch')), ('target_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_in', to='production.productionbatch'))], options={'ordering': ['-created_at', '-id']}),
        migrations.AddField(model_name='order', name='production_destination', field=models.CharField(choices=[('store', 'Store replenishment — add to Physical Store stock'), ('non_stock', 'Non-stock purpose — do not add to Physical Store stock')], default='store', help_text='Physical Store orders only: choose whether completed production enters Shelf Stock or is for a non-stock purpose.', max_length=12)),
        migrations.AddField(model_name='order', name='non_stock_purpose', field=models.CharField(blank=True, default='', max_length=255, help_text='Specific purpose when production is not going to Physical Store stock (e.g. Staff Welfare, Gift, Charity).')),
        migrations.CreateModel(name='OrderMaterialUsage', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('planned_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)), ('actual_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)), ('flexible', models.BooleanField(default=False)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='production.order')), ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='production.orderitem')), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'))], options={'ordering': ['order_item_id', 'raw_material__name']}),
        migrations.AddConstraint(model_name='ordermaterialusage', constraint=models.UniqueConstraint(fields=('order_item', 'raw_material'), name='unique_material_usage_per_order_item')),
        migrations.AlterField(model_name='order', name='customer_payment_method', field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Transfer', max_length=10)),
        migrations.AlterField(model_name='productionbatch', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='productionbatch', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='productionbatchreconciliation', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='productionbatchreconciliation', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='productionqualitycheck', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='productionqualitycheck', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='productionbatch', name='excess_stock_units', field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='productionbatch', name='excess_non_stock_units', field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='productionbatch', name='excess_non_stock_purpose', field=models.CharField(blank=True, default='', max_length=255)),
        migrations.AddField(model_name='orderitem', name='production_batch_qty', field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional production plan. Leave 0/blank to produce exactly the ordered quantity.', max_digits=12)),
        migrations.AddField(model_name='orderitem', name='production_piece_qty', field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional loose pieces in the production plan. Leave 0/blank to produce exactly the ordered quantity.', max_digits=12)),
        migrations.AddField(model_name='productionbatch', name='ordered_units', field=models.DecimalField(decimal_places=2, default=0, help_text='Customer/requested quantity kept separately from the production target.', max_digits=14)),
        migrations.AddField(model_name='productionbatch', name='planned_surplus_stock_units', field=models.DecimalField(decimal_places=2, default=0, help_text='Saleable planned overproduction retained as general Physical Store stock.', max_digits=14)),
    ]
