# Generated by Django 5.2.17 on 2026-10-02 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_query_pattern_indexes'),
        ('production', '0008_order_shared_base_material_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='base_material',
            field=models.ForeignKey(blank=True, help_text='The base material that every member order of this run draws from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_run_base_pools', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='base_material_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Overall quantity of the base material available to the whole run.', max_digits=14),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='production_basis',
            field=models.CharField(choices=[('product_quantity', 'Product quantity'), ('base_material', 'Base material')], default='product_quantity', help_text="Sized by each order's own quantities, or against one overall base-material pool shared by every member order.", max_length=24),
        ),
    ]
