# Generated by Django 5.2.17 on 2026-10-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_productionrun_shared_base_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionrun',
            name='base_material',
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='base_material_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text="Overall pool of the base material (taken from the member orders' products) available to the whole run.", max_digits=14),
        ),
    ]
