# Generated by Django 5.2.17 on 2026-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionrun_drop_base_material_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_option_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_option_value',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
