# Generated by Django 5.2.17 on 2026-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_orderitem_product_option_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commerce_addon_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
