# Generated by Django 5.2.17 on 2026-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_query_pattern_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product_option_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_option_value',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
