# Generated by Django 5.2.17 on 2026-10-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_product_option_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='commerce_addon_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
