from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.core.validators import FileExtensionValidator

def seed_system_roles(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Role = apps.get_model('accounts', 'Role')
    RoleModulePermission = apps.get_model('accounts', 'RoleModulePermission')
    system = [('stock_keeper', 'Stock Keeper'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('md_director', 'MD / Director'), ('business_admin', 'Business Admin'), ('superuser', 'Superuser')]
    defaults = {'stock_keeper': {'dashboard': (1, 0), 'inventory': (1, 1), 'procurement': (1, 1), 'production': (1, 1), 'sales': (1, 0), 'expenses': (0, 0), 'finance': (0, 0), 'reports': (1, 0), 'users': (0, 0)}, 'manager': {m: (1, 1) for m in ['dashboard', 'inventory', 'procurement', 'production', 'sales', 'expenses', 'finance', 'reports']} | {'users': (0, 0)}, 'accountant': {'dashboard': (1, 0), 'inventory': (1, 0), 'procurement': (1, 0), 'production': (1, 0), 'sales': (1, 0), 'expenses': (1, 1), 'finance': (1, 1), 'reports': (1, 1), 'users': (0, 0)}, 'md_director': {'dashboard': (1, 0), 'inventory': (1, 0), 'procurement': (1, 0), 'production': (1, 0), 'sales': (1, 0), 'expenses': (1, 0), 'finance': (1, 1), 'reports': (1, 1), 'users': (1, 0)}, 'business_admin': {m: (1, 1) for m in ['dashboard', 'inventory', 'procurement', 'production', 'sales', 'expenses', 'finance', 'reports', 'users']}, 'superuser': {m: (1, 1) for m in ['dashboard', 'inventory', 'procurement', 'production', 'sales', 'expenses', 'finance', 'reports', 'users']}}
    for business in Business.objects.all():
        for key, name in system:
            role, _ = Role.objects.get_or_create(business_id=business.pk, key=key, defaults={'name': name, 'is_system': True, 'active': True})
            for module, (view, edit) in defaults[key].items():
                RoleModulePermission.objects.get_or_create(role_id=role.pk, module=module, defaults={'can_view': bool(view), 'can_edit': bool(edit)})
def hide_superuser_role(apps, schema_editor):
    Role = apps.get_model('accounts', 'Role')
    Role.objects.filter(key='superuser', visible_to_admin=True).update(visible_to_admin=False)
def noop(apps, schema_editor):
    pass
MODULES = ('dashboard', 'inventory', 'procurement', 'production', 'sales', 'expenses', 'finance', 'reports', 'users')
def seed_existing_business_modules(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    BusinessModuleAccess = apps.get_model('accounts', 'BusinessModuleAccess')
    for business_id in Business.objects.values_list('id', flat=True):
        for module in MODULES:
            BusinessModuleAccess.objects.get_or_create(business_id=business_id, module=module, defaults={'enabled': True, 'source': 'existing'})
MODULES = ('dashboard', 'inventory', 'procurement', 'production', 'sales', 'expenses', 'finance', 'reports', 'users', 'commerce')
PLAN_MATRIX = {'starter': {'dashboard': 'full', 'inventory': 'full', 'sales': 'full', 'expenses': 'full', 'reports': 'basic', 'users': 'full'}, 'production': {'dashboard': 'full', 'inventory': 'full', 'procurement': 'full', 'production': 'full', 'sales': 'full', 'expenses': 'full', 'reports': 'full', 'users': 'full'}, 'business_pro': {m: 'full' for m in MODULES}}
def seed_plans_and_commerce_permissions(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Role = apps.get_model('accounts', 'Role')
    RolePermission = apps.get_model('accounts', 'RoleModulePermission')
    BusinessAccess = apps.get_model('accounts', 'BusinessModuleAccess')
    Plan = apps.get_model('accounts', 'SubscriptionPlan')
    PlanModule = apps.get_model('accounts', 'SubscriptionPlanModule')
    names = {'starter': 'STARTER', 'production': 'PRODUCTION', 'business_pro': 'BUSINESS PRO'}
    for code, name in names.items():
        plan, _ = Plan.objects.get_or_create(code=code, defaults={'name': name, 'monthly_price': 0, 'trial_days': 30, 'additional_service_discount_percent': 30})
        for module in MODULES:
            level = PLAN_MATRIX[code].get(module, 'none')
            PlanModule.objects.update_or_create(plan=plan, module=module, defaults={'enabled': level != 'none', 'level': level})
    for business_id in Business.objects.values_list('id', flat=True):
        BusinessAccess.objects.get_or_create(business_id=business_id, module='commerce', defaults={'enabled': False, 'source': 'existing'})
    for role in Role.objects.all():
        RolePermission.objects.get_or_create(role_id=role.id, module='commerce', defaults={'can_view': role.key in {'business_admin', 'superuser'}, 'can_edit': role.key in {'business_admin', 'superuser'}})
def migrate_storefront_access(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Role = apps.get_model('accounts', 'Role')
    RoleModulePermission = apps.get_model('accounts', 'RoleModulePermission')
    UserBusiness = apps.get_model('accounts', 'UserBusiness')
    UserModulePermission = apps.get_model('accounts', 'UserModulePermission')
    for business_id in Business.objects.values_list('id', flat=True).iterator():
        role = Role.objects.filter(business_id=business_id, key='pos_operator').first()
        if role is None:
            role_name = 'In-Premise POS'
            if Role.objects.filter(business_id=business_id, name=role_name).exists():
                role_name = 'In-Premise POS (System)'
            role = Role.objects.create(business_id=business_id, key='pos_operator', name=role_name, is_system=True, active=True, visible_to_admin=True)
        RoleModulePermission.objects.update_or_create(role_id=role.id, module='dashboard', defaults={'can_view': True, 'can_edit': False})
        RoleModulePermission.objects.update_or_create(role_id=role.id, module='pos', defaults={'can_view': True, 'can_edit': True})
        for module, _label in MODULE_CHOICES:
            if module in {'dashboard', 'pos'}:
                continue
            RoleModulePermission.objects.get_or_create(role_id=role.id, module=module, defaults={'can_view': False, 'can_edit': False})
    for membership_id in UserBusiness.objects.filter(commerce_storefront_access=True).values_list('id', flat=True).iterator():
        UserModulePermission.objects.update_or_create(membership_id=membership_id, module='pos', defaults={'can_view': True, 'can_edit': True})
MODULE_CHOICES = [('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management'), ('commerce', 'Commerce'), ('pos', 'In-Premise POS')]

class Migration(migrations.Migration):
    replaces = [
        ('accounts', '0002_roles_and_memberships'),
        ('accounts', '0003_role_visible_to_admin'),
        ('accounts', '0004_hide_superuser_role_from_admin'),
        ('accounts', '0005_alter_customuser_managers_alter_customuser_groups_and_more'),
        ('accounts', '0006_businessmoduleaccess'),
        ('accounts', '0007_subscription_plans_and_commerce_module'),
        ('accounts', '0008_subscription_yearly_and_gateways'),
        ('accounts', '0009_subscriptionpaymentsettings'),
        ('accounts', '0010_subscription_promotions_and_storefront_access'),
        ('accounts', '0011_marketingpromocampaign'),
        ('accounts', '0012_subscriptionpromotion_all_plans'),
        ('accounts', '0013_pos_permission_and_promotion_cycle'),
    ]
    dependencies = [("accounts", "0001_identity"), ("core", "0001_baseline")]
    operations = [
        migrations.CreateModel(name='Role', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('key', models.SlugField(max_length=60)), ('name', models.CharField(max_length=80)), ('is_system', models.BooleanField(default=False)), ('active', models.BooleanField(default=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.business'))], options={'ordering': ['name'], 'constraints': [models.UniqueConstraint(fields=('business', 'key'), name='unique_role_key_per_business'), models.UniqueConstraint(fields=('business', 'name'), name='unique_role_name_per_business')]}),
        migrations.CreateModel(name='RoleModulePermission', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30)), ('can_view', models.BooleanField(default=False)), ('can_edit', models.BooleanField(default=False)), ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.role'))], options={'ordering': ['module'], 'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='unique_role_module_permission')]}),
        migrations.CreateModel(name='UserBusiness', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('active', models.BooleanField(default=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='core.business')), ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.role')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL))], options={'constraints': [models.UniqueConstraint(fields=('user', 'business'), name='unique_user_business_membership')]}),
        migrations.CreateModel(name='UserModulePermission', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30)), ('can_view', models.BooleanField(blank=True, default=None, null=True)), ('can_edit', models.BooleanField(blank=True, default=None, null=True)), ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.userbusiness'))], options={'ordering': ['module'], 'constraints': [models.UniqueConstraint(fields=('membership', 'module'), name='unique_user_module_permission')]}),
        migrations.RunPython(seed_system_roles, migrations.RunPython.noop),
        migrations.AddField(model_name='role', name='visible_to_admin', field=models.BooleanField(default=True, help_text="Uncheck to keep this role visible only to the global superuser — for demo/review roles that aren't part of this business's normal operations. Business Admins won't see it in Roles & Access, can't open it directly, and can't assign it to a user.")),
        migrations.RunPython(hide_superuser_role, noop),
        migrations.AlterModelManagers(name='customuser', managers=[]),
        migrations.AlterField(model_name='customuser', name='groups', field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
        migrations.AlterField(model_name='customuser', name='user_permissions', field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
        migrations.CreateModel(name='BusinessModuleAccess', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management')], max_length=30)), ('enabled', models.BooleanField(default=True)), ('source', models.CharField(choices=[('default', 'Vertical default'), ('existing', 'Existing full access'), ('plan', 'Subscription plan')], default='default', max_length=12)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='core.business'))], options={'ordering': ['module'], 'constraints': [models.UniqueConstraint(fields=('business', 'module'), name='unique_business_module_access')]}),
        migrations.RunPython(seed_existing_business_modules, migrations.RunPython.noop),
        migrations.AlterField(model_name='rolemodulepermission', name='module', field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management'), ('commerce', 'Commerce')], max_length=30)),
        migrations.AlterField(model_name='usermodulepermission', name='module', field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management'), ('commerce', 'Commerce')], max_length=30)),
        migrations.AlterField(model_name='businessmoduleaccess', name='module', field=models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management'), ('commerce', 'Commerce')], max_length=30)),
        migrations.AlterField(model_name='businessmoduleaccess', name='source', field=models.CharField(choices=[('default', 'Service default'), ('existing', 'Existing full access'), ('plan', 'Subscription plan'), ('founder', 'Founder lifetime grant')], default='default', max_length=12)),
        migrations.CreateModel(name='SubscriptionPlan', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('code', models.CharField(choices=[('starter', 'STARTER'), ('production', 'PRODUCTION'), ('business_pro', 'BUSINESS PRO')], max_length=30, unique=True)), ('name', models.CharField(max_length=80)), ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('additional_service_discount_percent', models.DecimalField(decimal_places=2, default=30, help_text="Discount from the plan's normal monthly price for each additional service/business profile.", max_digits=5)), ('trial_days', models.PositiveSmallIntegerField(default=30)), ('active', models.BooleanField(default=True))], options={'ordering': ['monthly_price', 'id']}),
        migrations.CreateModel(name='SubscriptionPlanModule', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('inventory', 'Inventory'), ('procurement', 'Procurement'), ('production', 'Production Orders'), ('sales', 'Sales'), ('expenses', 'Expenses'), ('finance', 'Finance'), ('reports', 'Reports'), ('users', 'User Management'), ('commerce', 'Commerce')], max_length=30)), ('enabled', models.BooleanField(default=False)), ('level', models.CharField(choices=[('none', 'Not included'), ('basic', 'Basic'), ('full', 'Full')], default='full', max_length=10)), ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_entitlements', to='accounts.subscriptionplan'))], options={'ordering': ['module'], 'constraints': [models.UniqueConstraint(fields=('plan', 'module'), name='unique_plan_module')]}),
        migrations.CreateModel(name='BusinessSubscription', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('status', models.CharField(choices=[('trial', 'Free trial'), ('active', 'Paid'), ('expired', 'Expired'), ('founder', 'Founder lifetime')], default='trial', max_length=12)), ('started_at', models.DateTimeField(auto_now_add=True)), ('trial_ends_at', models.DateTimeField(blank=True, null=True)), ('paid_until', models.DateTimeField(blank=True, null=True)), ('founder_lifetime', models.BooleanField(default=False)), ('founder_granted_at', models.DateTimeField(blank=True, null=True)), ('founder_note', models.CharField(blank=True, default='', max_length=255)), ('founder_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder_grants_made', to=settings.AUTH_USER_MODEL)), ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.subscriptionplan')), ('primary_business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.business'))], options={'ordering': ['primary_business__name']}),
        migrations.CreateModel(name='SubscriptionService', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('is_primary', models.BooleanField(default=False)), ('added_at', models.DateTimeField(auto_now_add=True)), ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_service', to='core.business')), ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.businesssubscription'))], options={'ordering': ['-is_primary', 'business__name'], 'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('subscription',), name='one_primary_service_per_subscription')]}),
        migrations.CreateModel(name='BusinessFeatureAccess', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('feature', models.CharField(max_length=60)), ('enabled', models.BooleanField(default=False)), ('source', models.CharField(choices=[('default', 'Service default'), ('existing', 'Existing full access'), ('plan', 'Subscription plan'), ('founder', 'Founder lifetime grant')], default='plan', max_length=12)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='core.business'))], options={'ordering': ['feature'], 'constraints': [models.UniqueConstraint(fields=('business', 'feature'), name='unique_business_feature_access')]}),
        migrations.CreateModel(name='SubscriptionPayment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('service_count', models.PositiveSmallIntegerField(default=1)), ('months', models.PositiveSmallIntegerField(default=1)), ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=12)), ('reference', models.CharField(max_length=80, unique=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('paid_at', models.DateTimeField(blank=True, null=True)), ('notes', models.CharField(blank=True, default='', max_length=255)), ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscriptionplan')), ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='accounts.businesssubscription'))], options={'ordering': ['-created_at', '-id']}),
        migrations.RunPython(seed_plans_and_commerce_permissions, migrations.RunPython.noop),
        migrations.AddField(model_name='subscriptionplan', name='yearly_discount_percent', field=models.DecimalField(decimal_places=2, default=0, help_text='Discount applied to 12 months of the plan when paid yearly.', max_digits=5)),
        migrations.AddField(model_name='subscriptionpayment', name='billing_cycle', field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=12)),
        migrations.AddField(model_name='subscriptionpayment', name='provider', field=models.CharField(choices=[('paystack', 'Paystack'), ('monnify', 'Monnify'), ('manual', 'Manual / founder confirmation')], default='manual', max_length=12)),
        migrations.AddField(model_name='subscriptionpayment', name='provider_reference', field=models.CharField(blank=True, default='', max_length=160)),
        migrations.AddField(model_name='subscriptionpayment', name='checkout_url', field=models.URLField(blank=True, default='')),
        migrations.AddField(model_name='subscriptionpayment', name='provider_payload', field=models.JSONField(blank=True, default=dict)),
        migrations.AlterField(model_name='subscriptionpayment', name='status', field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
        migrations.CreateModel(name='SubscriptionPaymentSettings', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('paystack_enabled', models.BooleanField(default=True)), ('monnify_enabled', models.BooleanField(default=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payment_settings_updates', to=settings.AUTH_USER_MODEL))], options={'verbose_name': 'subscription payment setting', 'verbose_name_plural': 'subscription payment settings'}),
        migrations.AddField(model_name='userbusiness', name='commerce_storefront_access', field=models.BooleanField(default=False, help_text='Allow this staff member to use the in-premise Commerce Storefront / POS without granting general Commerce administration access.')),
        migrations.CreateModel(name='SubscriptionPromotion', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('reason', models.CharField(max_length=140)), ('discount_type', models.CharField(choices=[('percent', 'Percentage off'), ('amount', 'Fixed amount off')], max_length=12)), ('discount_value', models.DecimalField(decimal_places=2, max_digits=14)), ('starts_at', models.DateTimeField()), ('ends_at', models.DateTimeField()), ('active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_promotions_created', to=settings.AUTH_USER_MODEL)), ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.subscriptionplan'))], options={'ordering': ['-starts_at', '-id']}),
        migrations.AddIndex(model_name='subscriptionpromotion', index=models.Index(fields=['plan', 'active', 'starts_at', 'ends_at'], name='plan_promo_active_idx')),
        migrations.AddField(model_name='subscriptionpayment', name='base_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='subscriptionpayment', name='promotion', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.subscriptionpromotion')),
        migrations.AddField(model_name='subscriptionpayment', name='promotion_discount_amount', field=models.DecimalField(decimal_places=2, default=0, max_digits=14)),
        migrations.AddField(model_name='subscriptionpayment', name='promotion_reason', field=models.CharField(blank=True, default='', max_length=140)),
        migrations.CreateModel(name='MarketingPromoCampaign', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(help_text='Founder-only label for this campaign creative.', max_length=100)), ('content_html', models.TextField(help_text='Promotion text shown to customers on the public offer display.')), ('cta_label', models.CharField(default='See promotional plans', max_length=80)), ('animation_style', models.CharField(choices=[('kinetic', 'Kinetic reveal'), ('spotlight', 'Spotlight sweep'), ('parallax', 'Parallax float'), ('marquee', 'Marquee energy')], default='kinetic', max_length=16)), ('theme', models.CharField(choices=[('midnight', 'Midnight'), ('ember', 'Ember'), ('paper', 'Paper'), ('gold', 'Gold')], default='midnight', max_length=16)), ('priority', models.PositiveSmallIntegerField(default=50, help_text='Higher numbers appear first if several promotions are live.')), ('image', models.ImageField(blank=True, upload_to='marketing/promotions/%Y/%m/')), ('video', models.FileField(blank=True, upload_to='marketing/promotions/%Y/%m/', validators=[FileExtensionValidator(['mp4', 'webm', 'mov'])])), ('video_poster', models.ImageField(blank=True, upload_to='marketing/promotions/%Y/%m/')), ('media_alt', models.CharField(blank=True, default='', max_length=180)), ('active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_promo_campaigns_created', to=settings.AUTH_USER_MODEL)), ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaign', to='accounts.subscriptionpromotion'))], options={'ordering': ['-priority', 'id']}),
        migrations.AddIndex(model_name='marketingpromocampaign', index=models.Index(fields=['active', 'priority'], name='marketing_campaign_idx')),
        migrations.AlterField(model_name='subscriptionpromotion', name='plan', field=models.ForeignKey(blank=True, help_text='Leave blank when this promotion applies to every active plan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.subscriptionplan')),
        migrations.AddField(model_name='subscriptionpromotion', name='applies_to_all_plans', field=models.BooleanField(default=False, help_text="Apply this single promotion to every active subscription plan using each plan's own base price.")),
        migrations.AddField(model_name='subscriptionpromotion', name='billing_cycle', field=models.CharField(choices=[('both', 'Monthly and yearly'), ('monthly', 'Monthly only'), ('yearly', 'Yearly only')], default='both', help_text='Limit this promotion to monthly payments, yearly payments, or both.', max_length=12)),
        migrations.AlterField(model_name='rolemodulepermission', name='module', field=models.CharField(choices=MODULE_CHOICES, max_length=30)),
        migrations.AlterField(model_name='usermodulepermission', name='module', field=models.CharField(choices=MODULE_CHOICES, max_length=30)),
        migrations.AlterField(model_name='businessmoduleaccess', name='module', field=models.CharField(choices=MODULE_CHOICES, max_length=30)),
        migrations.AlterField(model_name='subscriptionplanmodule', name='module', field=models.CharField(choices=MODULE_CHOICES, max_length=30)),
        migrations.RunPython(migrate_storefront_access, migrations.RunPython.noop),
        migrations.RemoveField(model_name='userbusiness', name='commerce_storefront_access'),
    ]
