# Generated by Django 5.2.17 on 2026-10-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_payroll_runs_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['batch__staff_count', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollStaffBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_count', models.PositiveIntegerField(help_text='Extra active payroll staff this batch adds.')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'payroll staff batches',
                'ordering': ['plan__monthly_price', 'staff_count', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='payrolladdontier',
            options={'ordering': ['plan__monthly_price', models.OrderBy(models.F('staff_limit'), nulls_last=True), 'id']},
        ),
        migrations.AddField(
            model_name='payrolladdontier',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='Cover unlimited active payroll staff on this plan.'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payroll_batch_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payroll_batch_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='payrolladdontier',
            name='staff_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum active payroll staff covered by this tier. Leave empty when unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Plan subscription'), ('payroll_addon', 'Payroll add-on'), ('payroll_batch', 'Payroll extra-staff batch')], default='subscription', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payrolladdontier',
            constraint=models.UniqueConstraint(condition=models.Q(('unlimited', True)), fields=('plan',), name='unique_unlimited_payroll_tier_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='payrolladdontier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff_limit__isnull', True), ('unlimited', True)), models.Q(('staff_limit__isnull', False), ('unlimited', False)), _connector='OR'), name='payroll_tier_limit_matches_unlimited'),
        ),
        migrations.AddField(
            model_name='businesspayrollbatch',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounts.businesspayrolladdon'),
        ),
        migrations.AddField(
            model_name='payrollstaffbatch',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_staff_batches', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='businesspayrollbatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='accounts.payrollstaffbatch'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payroll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='accounts.payrollstaffbatch'),
        ),
        migrations.AddConstraint(
            model_name='payrollstaffbatch',
            constraint=models.UniqueConstraint(fields=('plan', 'staff_count'), name='unique_payroll_batch_plan_staff'),
        ),
        migrations.AddConstraint(
            model_name='payrollstaffbatch',
            constraint=models.CheckConstraint(condition=models.Q(('staff_count__gte', 1)), name='payroll_batch_staff_positive'),
        ),
        migrations.AddConstraint(
            model_name='businesspayrollbatch',
            constraint=models.UniqueConstraint(fields=('addon', 'batch'), name='unique_business_payroll_batch'),
        ),
        migrations.AddConstraint(
            model_name='businesspayrollbatch',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='business_payroll_batch_qty_positive'),
        ),
    ]
