from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    replaces = [
        ('procurement', '0001_initial'),
        ('procurement', '0002_purchase_stock_products'),
    ]
    dependencies = [("core", "0001_baseline"), ("inventory", "0001_baseline"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='PurchaseOrder', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('supplier', models.CharField(blank=True, max_length=120)), ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received')], default='draft', max_length=10)), ('received_date', models.DateField(blank=True, null=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'))], options={'ordering': ['-date', '-id']}),
        migrations.CreateModel(name='PurchaseOrderItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('qty', models.DecimalField(decimal_places=2, max_digits=12)), ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)), ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.rawmaterial'))], options={'abstract': False}),
        migrations.AddField(model_name='purchaseorder', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.CreateModel(name='RawMaterialCostSnapshot', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('effective_date', models.DateField()), ('purchase_unit_cost', models.DecimalField(decimal_places=2, max_digits=12)), ('usage_unit_cost', models.DecimalField(decimal_places=6, max_digits=16)), ('supplier', models.CharField(blank=True, max_length=120)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_rawmaterialcostsnapshot_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rawmaterialcostsnapshot_created', to=settings.AUTH_USER_MODEL)), ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_snapshots', to='procurement.purchaseorderitem')), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_snapshots', to='inventory.rawmaterial'))], options={'ordering': ['-effective_date', '-id']}),
        migrations.AlterField(model_name='rawmaterialcostsnapshot', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='rawmaterialcostsnapshot', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='purchaseorder', name='payment_status', field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=10)),
        migrations.AddField(model_name='purchaseorder', name='payment_method', field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Transfer', max_length=10)),
        migrations.CreateModel(name='SupplierPayment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('supplier', models.CharField(max_length=120)), ('amount', models.DecimalField(decimal_places=2, max_digits=16)), ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Transfer', 'Transfer')], default='Transfer', max_length=10)), ('reference', models.CharField(blank=True, default='', max_length=80)), ('notes', models.CharField(blank=True, default='', max_length=255)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_supplierpayment_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_supplierpayment_created', to=settings.AUTH_USER_MODEL)), ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.PROTECT, related_name='payments', to='procurement.purchaseorder'))], options={'ordering': ['-date', '-id']}),
        migrations.AlterField(model_name='supplierpayment', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='supplierpayment', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='purchaseorder', name='account', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.cashaccount')),
        migrations.AddField(model_name='supplierpayment', name='account', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='core.cashaccount')),
        migrations.AlterField(model_name='purchaseorderitem', name='raw_material', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.rawmaterial')),
        migrations.AddField(model_name='purchaseorderitem', name='finished_good', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.finishedgood')),
        migrations.AddConstraint(model_name='purchaseorderitem', constraint=models.CheckConstraint(condition=models.Q(('finished_good__isnull', True), ('raw_material__isnull', False)) | models.Q(('finished_good__isnull', False), ('raw_material__isnull', True)), name='purchase_item_has_exactly_one_stock_item')),
    ]
