# Generated by INPROFIC audit-query workspace implementation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("core", "0001_baseline"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="AuditQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(max_length=40)),
                ("record_label", models.CharField(blank=True, default="", max_length=180)),
                ("record_model", models.CharField(blank=True, default="", max_length=120)),
                ("record_id", models.CharField(blank=True, default="", max_length=80)),
                ("subject", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=10)),
                ("status", models.CharField(choices=[("open", "Open"), ("reviewing", "Under review"), ("answered", "Answered"), ("closed", "Closed")], default="open", max_length=12)),
                ("response", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_audit_queries", to=settings.AUTH_USER_MODEL)),
                ("answered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="answered_audit_queries", to=settings.AUTH_USER_MODEL)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="core_auditquery_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="core_auditquery_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["status", "-created_at", "-id"], "indexes": [models.Index(fields=["business", "status", "created_at"], name="audit_query_status_idx")]},
        ),
    ]
