# Generated by Django 5.2.17 on 2026-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditquery_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='vertical',
            field=models.CharField(choices=[('bakery', 'Bakery'), ('restaurant', 'Restaurant / Food Service'), ('general', 'General Production'), ('wholesale', 'Wholesale / Distribution'), ('retail', 'Retail Store')], default='bakery', max_length=20),
        ),
    ]
