# Generated by Django 5.2.17 on 2026-10-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_query_pattern_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='contact_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
