"""
Django settings for storetrack project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Domain apps live under apps/, added to sys.path so INSTALLED_APPS can use
# plain names ('inventory') instead of dotted paths ('apps.inventory') —
# mirrors the ChurchForce apps/ convention. Centralized here (rather than
# duplicated in manage.py + asgi.py) since this project has one entrypoint.
sys.path.insert(0, str(BASE_DIR / "apps"))


def env_bool(name, default=False):
    """Read common true/false environment spellings without case surprises."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name):
    return [value.strip() for value in os.environ.get(name, "").split(",") if value.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Environment variable loaded dynamically via WSGI or local .env setup
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-2em27qpg%ghma2nfqc3e59d*m@!@m76ef_ms7c(o3e1u0th14*",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

# Configure allowed domains safely. Fallback to localhost if nothing is provided.
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS") or ["127.0.0.1", "localhost"]
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# Render supplies its assigned hostname automatically. Custom domains still go
# in ALLOWED_HOSTS and CSRF_TRUSTED_ORIGINS explicitly.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
    'inventory',
    'procurement',
    'production',
    'sales',
    'expenses',
    'commerce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.performance.PerformanceDiagnosticMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.BusinessMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'storetrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.business',
            ],
        },
    },
]

WSGI_APPLICATION = 'storetrack.wsgi.application'
ASGI_APPLICATION = 'storetrack.asgi.application'

# A single-process installation needs no external service. Set
# CHANNEL_REDIS_URL before adding ASGI workers or running multiple instances so
# notifications can cross process boundaries.
CHANNEL_REDIS_URL = os.environ.get("CHANNEL_REDIS_URL", "").strip()
if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [CHANNEL_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Read the URL string from the environment variable (e.g. from your .env or .env.prod file)
db_url = os.environ.get('DATABASE_URL', '').strip()

if db_url.startswith(('postgres://', 'postgresql://')):
    db_conn_max_age = int(os.environ.get("DB_CONN_MAX_AGE", "0"))
    db_pool_max_size = int(os.environ.get("DB_POOL_MAX_SIZE", "0"))
    if db_pool_max_size and db_conn_max_age:
        raise ImproperlyConfigured(
            "DB_POOL_MAX_SIZE requires DB_CONN_MAX_AGE=0."
        )
    # A psycopg pool already reuses connections. A Django health check adds an
    # extra request-time database round trip, so keep it opt-in when pooling
    # instead of paying that cost on every warm navigation.
    database = dj_database_url.parse(
        db_url,
        conn_max_age=db_conn_max_age,
        conn_health_checks=env_bool("DB_CONN_HEALTH_CHECKS", not bool(db_pool_max_size)),
        ssl_require=env_bool("DB_SSL_REQUIRE", not DEBUG),
    )
    if db_pool_max_size:
        db_pool_min_size = int(os.environ.get("DB_POOL_MIN_SIZE", "0"))
        if db_pool_min_size < 0 or db_pool_min_size > db_pool_max_size:
            raise ImproperlyConfigured(
                "DB_POOL_MIN_SIZE must be between 0 and DB_POOL_MAX_SIZE."
            )
        database.setdefault("OPTIONS", {})["pool"] = {
            "min_size": db_pool_min_size,
            "max_size": db_pool_max_size,
            "timeout": int(os.environ.get("DB_POOL_TIMEOUT", "10")),
        }
    DATABASES = {
        'default': database,
    }
elif db_url.startswith('sqlite:////'):
    # Production absolute path parsing (Handles 4 slashes)
    db_path = Path(db_url.replace('sqlite:////', '/'))
elif db_url.startswith('sqlite:///'):
    # Local relative path configuration (Handles 3 slashes)
    db_path = BASE_DIR / db_url.replace('sqlite:///','')
else:
    # Standard fallback path if no environment variable is found
    db_path = BASE_DIR / 'db.sqlite3'

if not db_url.startswith(('postgres://', 'postgresql://')):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
            'OPTIONS': {
                'timeout': 20,  # Wait briefly instead of immediately failing on a concurrent local write.
                # Django 5.1+ supports IMMEDIATE SQLite transactions. Acquiring
                # the write reservation at transaction start avoids DEFERRED
                # read-to-write upgrade failures when a concurrent notification
                # or request is writing at the same time.
                'transaction_mode': 'IMMEDIATE',
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE= 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Required for running 'collectstatic' on PythonAnywhere
MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))
RUNNING_TESTS = "test" in sys.argv

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG or RUNNING_TESTS
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Cloudflare R2 is opt-in. Leaving every R2 variable empty keeps local media,
# which is the existing PythonAnywhere behavior.
_r2_settings = {
    "access_key": os.environ.get("R2_ACCESS_KEY_ID", "").strip(),
    "secret_key": os.environ.get("R2_SECRET_ACCESS_KEY", "").strip(),
    "bucket_name": os.environ.get("R2_BUCKET_NAME", "").strip(),
    "endpoint_url": os.environ.get("R2_ENDPOINT_URL", "").strip().rstrip("/"),
}
if any(_r2_settings.values()) and not all(_r2_settings.values()):
    raise ImproperlyConfigured(
        "R2 media storage requires R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, "
        "R2_BUCKET_NAME, and R2_ENDPOINT_URL together."
    )

if all(_r2_settings.values()):
    r2_custom_domain = os.environ.get("R2_CUSTOM_DOMAIN", "").strip().rstrip("/")
    r2_custom_domain = r2_custom_domain.removeprefix("https://").removeprefix("http://")
    r2_media_location = os.environ.get("R2_MEDIA_LOCATION", "media").strip().strip("/") or "media"
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            **_r2_settings,
            "region_name": os.environ.get("R2_REGION_NAME", "auto"),
            "location": r2_media_location,
            "default_acl": None,
            "file_overwrite": False,
            "querystring_auth": not bool(r2_custom_domain),
            "custom_domain": r2_custom_domain or None,
            "object_parameters": {"CacheControl": "max-age=86400"},
        },
    }
    if r2_custom_domain:
        MEDIA_URL = f"https://{r2_custom_domain}/{r2_media_location}/"

# Proxy-aware production security. Render terminates TLS before forwarding to
# Daphne; PythonAnywhere can enable the same settings from .env.prod.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if env_bool(
    "TRUST_PROXY_SSL_HEADER", bool(RENDER_EXTERNAL_HOSTNAME)
) else None
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", False)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

# Used only by authenticated external maintenance endpoints.
CRON_SECRET = os.environ.get("CRON_SECRET", "")

# Web Push uses one deployment-wide VAPID key pair. The public key is safe to
# expose to browsers; the private key must remain an environment secret.
WEB_PUSH_VAPID_PUBLIC_KEY = os.environ.get("WEB_PUSH_VAPID_PUBLIC_KEY", "").strip()
WEB_PUSH_VAPID_PRIVATE_KEY = os.environ.get("WEB_PUSH_VAPID_PRIVATE_KEY", "").strip()
WEB_PUSH_VAPID_SUBJECT = os.environ.get("WEB_PUSH_VAPID_SUBJECT", "").strip()
WEB_PUSH_TIMEOUT_SECONDS = float(os.environ.get("WEB_PUSH_TIMEOUT_SECONDS", "5"))

# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
# Authenticated browsers return straight to the workspace while active. After
# this idle period, re-authentication is required instead of showing marketing.
AUTHENTICATED_IDLE_TIMEOUT_SECONDS = int(os.environ.get("INPROFIC_IDLE_TIMEOUT_SECONDS", "28800"))
# Persist the rolling activity timestamp at most once per interval. This keeps
# the idle timeout accurate without turning every authenticated GET into a
# database-backed session write.
AUTHENTICATED_ACTIVITY_WRITE_INTERVAL_SECONDS = int(
    os.environ.get("INPROFIC_ACTIVITY_WRITE_INTERVAL_SECONDS", "60")
)

# Production-safe warm-request diagnostics. This is intentionally opt-in and
# does not enable DEBUG or Django's query capture. It records only aggregate
# request/database timings and logs requests that cross the configured limit.
PERF_DIAGNOSTICS = env_bool("PERF_DIAGNOSTICS", False)
PERF_SLOW_REQUEST_MS = int(os.environ.get("PERF_SLOW_REQUEST_MS", "500"))
PERF_SERVER_TIMING = env_bool("PERF_SERVER_TIMING", True)
PERF_EXCLUDED_PREFIXES = tuple(
    env_list("PERF_EXCLUDED_PREFIXES")
    or ["/health/", "/ops/", "/static/", "/media/", "/ws/", "/manifest.webmanifest", "/service-worker.js", "/pwa/"]
)

# Render runs this service as one Daphne process. cached_db keeps the durable
# django_session row as the source of truth while avoiding a PostgreSQL session
# read on every warm page navigation. It is opt-in so PythonAnywhere/local
# behavior is unchanged unless explicitly enabled.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": os.environ.get("DJANGO_CACHE_LOCATION", "inprofic-runtime"),
        "OPTIONS": {"MAX_ENTRIES": int(os.environ.get("DJANGO_CACHE_MAX_ENTRIES", "5000"))},
    }
}
SESSION_ENGINE = (
    "django.contrib.sessions.backends.cached_db"
    if env_bool("USE_CACHED_DB_SESSIONS", False)
    else "django.contrib.sessions.backends.db"
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "performance_console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "inprofic.performance": {
            "handlers": ["performance_console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.CustomUser"

# Subscription payment gateways. Keep all secrets in environment variables.
# Paystack uses the same API base URL for test/live; the key selects the mode.
PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY", "")
PAYSTACK_PUBLIC_KEY = os.environ.get("PAYSTACK_PUBLIC_KEY", "")

# Use https://sandbox.monnify.com while testing and https://api.monnify.com in production.
MONNIFY_API_KEY = os.environ.get("MONNIFY_API_KEY", "")
MONNIFY_SECRET_KEY = os.environ.get("MONNIFY_SECRET_KEY", "")
MONNIFY_CONTRACT_CODE = os.environ.get("MONNIFY_CONTRACT_CODE", "")
MONNIFY_BASE_URL = os.environ.get("MONNIFY_BASE_URL", "https://api.monnify.com")

# PWA service-worker build identity. Render exposes the deployed git commit; a manual override is also supported.
PWA_BUILD_VERSION = os.getenv("PWA_BUILD_VERSION") or os.getenv("RENDER_GIT_COMMIT") or "dev"
