from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone

def classify_non_production_products(apps, schema_editor):
    FinishedGood = apps.get_model('inventory', 'FinishedGood')
    Business = apps.get_model('core', 'Business')
    non_production_ids = Business.objects.filter(vertical__in=['wholesale', 'retail']).values_list('id', flat=True)
    FinishedGood.objects.filter(business_id__in=non_production_ids).update(source_type='purchased_for_resale')

class Migration(migrations.Migration):
    initial = True
    replaces = [
        ('inventory', '0001_initial'),
        ('inventory', '0002_recipeitem_flexible_usage'),
        ('inventory', '0003_alter_operationalsupplydispense_business_and_more'),
        ('inventory', '0004_rawmaterial_stock_3dp'),
        ('inventory', '0005_market_stock_lots'),
        ('inventory', '0006_stock_product_purchase_movement'),
        ('inventory', '0007_widen_usage_conversion_precision'),
        ('inventory', '0008_finishedgood_source_type'),
    ]
    dependencies = [("core", "0001_baseline"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='FinishedGood', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('unit', models.CharField(help_text='loaf, plate, box…', max_length=20)), ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'))], options={'ordering': ['name']}),
        migrations.CreateModel(name='RawMaterial', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120)), ('unit', models.CharField(help_text='kg, litre, pack…', max_length=20)), ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business'))], options={'ordering': ['name']}),
        migrations.CreateModel(name='RecipeItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('qty_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=12)), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.finishedgood')), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial'))]),
        migrations.AddConstraint(model_name='finishedgood', constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_finished_good_per_business')),
        migrations.AddConstraint(model_name='rawmaterial', constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_raw_material_per_business')),
        migrations.AlterUniqueTogether(name='recipeitem', unique_together={('finished_good', 'raw_material')}),
        migrations.AddField(model_name='finishedgood', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='rawmaterial', name='conversion_factor', field=models.DecimalField(decimal_places=4, default=1, help_text='How many usage units in 1 purchase unit. E.g. 1 bag = 50 kg → 50. Same unit both ways → 1.', max_digits=12)),
        migrations.AddField(model_name='rawmaterial', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='rawmaterial', name='purchase_unit', field=models.CharField(blank=True, default='', help_text='The unit you buy in — bag, carton, bowl…', max_length=20)),
        migrations.AddField(model_name='rawmaterial', name='usage_unit', field=models.CharField(blank=True, default='', help_text='The unit stock/recipes are tracked in — kg, sachet, litre…', max_length=20)),
        migrations.RemoveField(model_name='rawmaterial', name='unit'),
        migrations.AlterField(model_name='rawmaterial', name='conversion_factor', field=models.DecimalField(decimal_places=2, default=1, help_text='How many usage units in 1 purchase unit. E.g. 1 bag = 50 kg → 50. Same unit both ways → 1.', max_digits=12)),
        migrations.AddField(model_name='rawmaterial', name='package_qty', field=models.DecimalField(decimal_places=2, default=1, help_text='How much is inside ONE purchase unit. E.g. 1 bag = 50 → 50.', max_digits=12)),
        migrations.AddField(model_name='rawmaterial', name='package_unit', field=models.CharField(blank=True, default='', help_text="The unit package_qty is measured in — kg, g, litre… (what's printed on the pack)", max_length=20)),
        migrations.AddField(model_name='rawmaterial', name='usage_conversion_factor', field=models.DecimalField(decimal_places=2, default=1, help_text="How many usage units in ONE package_unit. Standard: kg→g is 1000, litre→ml is 1000, same unit both ways is 1. Non-standard (spoon, cap…): count it yourself, e.g. 'my spoon holds 5g' → if package_unit is kg, that's 200 spoons per kg → 200.", max_digits=12)),
        migrations.AlterField(model_name='rawmaterial', name='conversion_factor', field=models.DecimalField(decimal_places=2, default=1, max_digits=12)),
        migrations.AlterField(model_name='rawmaterial', name='purchase_unit', field=models.CharField(blank=True, default='', help_text='What you buy — bag, carton, pack…', max_length=20)),
        migrations.AlterField(model_name='rawmaterial', name='usage_unit', field=models.CharField(blank=True, default='', help_text='The fine unit recipes actually consume — kg, g, spoon, cap…', max_length=20)),
        migrations.RemoveField(model_name='rawmaterial', name='conversion_factor'),
        migrations.RenameField(model_name='recipeitem', old_name='qty_per_unit', new_name='qty_per_batch'),
        migrations.AddField(model_name='finishedgood', name='units_per_batch', field=models.DecimalField(decimal_places=2, default=1, help_text="How many individual units one production batch makes, e.g. 41 loaves per batch. Recipe quantities are per BATCH, not per unit. Leave at 1 if you don't produce in batches.", max_digits=12)),
        migrations.AlterField(model_name='finishedgood', name='reorder_level', field=models.DecimalField(decimal_places=2, default=0, help_text='In individual units, not batches.', max_digits=12)),
        migrations.AddField(model_name='finishedgood', name='total_produced', field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative all-time production (customer orders + physical store restocks). Never decreases — a running total, not current stock.', max_digits=14)),
        migrations.AlterField(model_name='finishedgood', name='stock', field=models.DecimalField(decimal_places=2, default=0, help_text='Physical store (shelf) stock — available to sell right now.', max_digits=12)),
        migrations.AlterField(model_name='recipeitem', name='qty_per_batch', field=models.DecimalField(decimal_places=2, default=0, max_digits=12)),
        migrations.AddField(model_name='finishedgood', name='total_delivered_to_customers', field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative units delivered via completed customer orders. Only updates when an order is completed — same timing as physical store stock, not when merely ordered.', max_digits=14)),
        migrations.CreateModel(name='StockMovement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('movement_type', models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('adjustment', 'Adjustment')], max_length=30)), ('quantity', models.DecimalField(decimal_places=2, help_text="Signed quantity in the item's stock tracking unit.", max_digits=14)), ('balance_after', models.DecimalField(decimal_places=2, help_text='Stock balance immediately after this movement.', max_digits=14)), ('occurred_at', models.DateTimeField(auto_now_add=True)), ('note', models.CharField(blank=True, default='', max_length=255)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)), ('finished_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.finishedgood')), ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.rawmaterial'))], options={'ordering': ['-occurred_at']}),
        migrations.AddField(model_name='stockmovement', name='affects_stock', field=models.BooleanField(default=True, help_text="Whether this movement changes the item's physical stock balance.")),
        migrations.AddField(model_name='rawmaterial', name='category', field=models.CharField(choices=[('ingredient', 'Ingredient'), ('packaging', 'Packaging'), ('production_supply', 'Production supply (gas, fuel, etc.)'), ('operational_supply', 'Operational supply (gloves, cleaning, etc.)')], default='ingredient', help_text='Classifies how the material is used. Operational supplies are not tied to a production recipe.', max_length=24)),
        migrations.CreateModel(name='ProductionMaterial', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('qty_per_batch', models.DecimalField(decimal_places=2, default=0, max_digits=12)), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_materials', to='inventory.finishedgood')), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_links', to='inventory.rawmaterial'))], options={'ordering': ['raw_material__name'], 'unique_together': {('finished_good', 'raw_material')}}),
        migrations.AlterField(model_name='rawmaterial', name='category', field=models.CharField(choices=[('ingredient', 'Ingredient'), ('packaging', 'Packaging'), ('production_supply', 'Production supply (Gas)'), ('operational_supply', 'Operational supply (Gloves, Cleaning, etc.)')], default='ingredient', help_text='Classifies how the material is used. Operational supplies are not tied to a production recipe.', max_length=24)),
        migrations.AlterField(model_name='rawmaterial', name='cost_per_unit', field=models.DecimalField(default=0, max_digits=16, decimal_places=6)),
        migrations.AlterField(model_name='finishedgood', name='stock', field=models.DecimalField(blank=True, default=None, help_text='Physical store (shelf) stock. Leave blank when this product is not stocked in the physical store.', max_digits=12, decimal_places=2, null=True)),
        migrations.AlterField(model_name='finishedgood', name='reorder_level', field=models.DecimalField(blank=True, default=None, help_text='Physical-store reorder threshold in individual units. Leave blank when this product is not stocked in the physical store.', max_digits=12, decimal_places=2, null=True)),
        migrations.CreateModel(name='FinishedGoodChannelPrice', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('channel', models.CharField(choices=[('physical_store', 'Physical Store'), ('distribution', 'Distribution'), ('online', 'Online')], max_length=20)), ('price', models.DecimalField(decimal_places=2, max_digits=12)), ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_prices', to='inventory.finishedgood'))], options={'ordering': ['channel'], 'unique_together': {('finished_good', 'channel')}}),
        migrations.AlterField(model_name='finishedgood', name='reorder_level', field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='For Physical Store ONLY.', max_digits=12, null=True)),
        migrations.AlterField(model_name='finishedgood', name='stock', field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Optional - Physical Store (shelf) Stock.', max_digits=12, null=True)),
        migrations.CreateModel(name='InventoryLocation', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=80)), ('location_type', models.CharField(default='store', max_length=30)), ('active', models.BooleanField(default=True)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_inventorylocation_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_inventorylocation_created', to=settings.AUTH_USER_MODEL))], options={'ordering': ['name'], 'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_inventory_location_per_business')]}),
        migrations.CreateModel(name='StockAdjustment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('quantity', models.DecimalField(decimal_places=2, max_digits=14)), ('reason', models.CharField(choices=[('count', 'Physical count correction'), ('wastage', 'Wastage / spoilage'), ('damage', 'Damage'), ('return_customer', 'Customer return'), ('return_supplier', 'Supplier return'), ('internal', 'Business use'), ('charity', 'Charity / donation'), ('staff', 'Staff issue'), ('other', 'Other')], default='count', max_length=30)), ('description', models.CharField(max_length=255)), ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=16)), ('reversed', models.BooleanField(default=False)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stockadjustment_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stockadjustment_created', to=settings.AUTH_USER_MODEL)), ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.rawmaterial')), ('finished_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.finishedgood')), ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation'))], options={'ordering': ['-date', '-id']}),
        migrations.AddField(model_name='stockmovement', name='reference', field=models.CharField(blank=True, default='', max_length=80)),
        migrations.AddField(model_name='stockmovement', name='unit_value', field=models.DecimalField(decimal_places=6, default=0, max_digits=16)),
        migrations.AddField(model_name='stockmovement', name='location', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventorylocation')),
        migrations.AlterField(model_name='stockmovement', name='movement_type', field=models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('fg_unpaid_issue', 'Unpaid product issue'), ('adjustment', 'Adjustment')], max_length=30)),
        migrations.AlterField(model_name='inventorylocation', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='inventorylocation', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='stockadjustment', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='stockadjustment', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='stockmovement', name='movement_type', field=models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('fg_unpaid_issue', 'Unpaid product issue'), ('operational_dispense', 'Operational supply dispense'), ('adjustment', 'Adjustment')], max_length=30)),
        migrations.AlterField(model_name='stockmovement', name='balance_after', field=models.DecimalField(blank=True, decimal_places=2, help_text='Stock balance immediately after this movement. Null for non-stock events.', max_digits=14, null=True)),
        migrations.CreateModel(name='OperationalSupplyDispense', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('date', models.DateField()), ('quantity', models.DecimalField(decimal_places=2, max_digits=14)), ('reason', models.CharField(choices=[('cleaning', 'Cleaning / sanitation'), ('staff', 'Staff use'), ('office', 'Office / administrative use'), ('maintenance', 'Maintenance'), ('charity', 'Charity / service'), ('other', 'Other')], default='other', max_length=20)), ('description', models.CharField(max_length=255)), ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_operationalsupplydispense_set', to='core.business')), ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_operationalsupplydispense_created', to=settings.AUTH_USER_MODEL)), ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operational_dispenses', to='inventory.inventorylocation')), ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_dispenses', to='inventory.rawmaterial'))], options={'ordering': ['-date', '-id']}),
        migrations.AddField(model_name='recipeitem', name='flexible_usage', field=models.BooleanField(default=False, help_text='Allow the quantity per batch to be adjusted when the production order is approved (useful for yeast or other urgency-sensitive ingredients).')),
        migrations.AlterField(model_name='operationalsupplydispense', name='business', field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
        migrations.AlterField(model_name='operationalsupplydispense', name='created_by', field=models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(model_name='stockmovement', name='movement_type', field=models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('fg_unpaid_issue', 'Unpaid product issue'), ('fg_wastage', 'Production wastage'), ('operational_dispense', 'Operational supply dispense'), ('adjustment', 'Adjustment')], max_length=30)),
        migrations.AlterField(model_name='rawmaterial', name='stock', field=models.DecimalField(decimal_places=3, default=0, max_digits=13)),
        migrations.AlterField(model_name='stockmovement', name='quantity', field=models.DecimalField(decimal_places=3, help_text="Signed quantity in the item's stock tracking unit.", max_digits=15)),
        migrations.AlterField(model_name='stockmovement', name='balance_after', field=models.DecimalField(blank=True, decimal_places=3, help_text='Stock balance immediately after this movement. Null for non-stock events.', max_digits=15, null=True)),
        migrations.AddField(model_name='finishedgood', name='transferred_market_stock', field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining shelf stock that entered through an explicit Market Stock transfer. This is the only shelf-sale allowance for products not normally configured for Physical Store stock.', max_digits=14)),
        migrations.AlterField(model_name='stockmovement', name='movement_type', field=models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_sale', 'Finished goods sale'), ('fg_unpaid_issue', 'Unpaid product issue'), ('fg_wastage', 'Production wastage'), ('fg_market_production', 'Production received into Distribution Market Stock'), ('fg_market_release', 'Market Stock released to distributor'), ('fg_market_return', 'Redistributable Distribution return'), ('fg_market_transfer', 'Market Stock transferred to Physical Store'), ('fg_market_expiry', 'Expired Market Stock write-off'), ('fg_distribution_damage', 'Damaged Distribution return'), ('operational_dispense', 'Operational supply dispense'), ('adjustment', 'Adjustment')], max_length=30)),
        migrations.AlterField(model_name='stockmovement', name='movement_type', field=models.CharField(choices=[('raw_purchase', 'Raw material purchase'), ('raw_consumption', 'Raw material consumption'), ('fg_production', 'Finished goods production'), ('fg_purchase', 'Stock product purchase'), ('fg_sale', 'Finished goods sale'), ('fg_unpaid_issue', 'Unpaid product issue'), ('fg_wastage', 'Production wastage'), ('fg_market_production', 'Production received into Distribution Market Stock'), ('fg_market_release', 'Market Stock released to distributor'), ('fg_market_return', 'Redistributable Distribution return'), ('fg_market_transfer', 'Market Stock transferred to Physical Store'), ('fg_market_expiry', 'Expired Market Stock write-off'), ('fg_distribution_damage', 'Damaged Distribution return'), ('operational_dispense', 'Operational supply dispense'), ('adjustment', 'Adjustment')], max_length=30)),
        migrations.AlterField(model_name='rawmaterial', name='usage_conversion_factor', field=models.DecimalField(decimal_places=6, default=1, help_text="How many usage units in ONE package_unit. Standard: kg→g is 1000, litre→ml is 1000, same unit both ways is 1. Non-standard (spoon, cap…): count it yourself, e.g. 'my spoon holds 5g' → if package_unit is kg, that's 200 spoons per kg → 200.", max_digits=16)),
        migrations.AddField(model_name='finishedgood', name='source_type', field=models.CharField(choices=[('made_in_house', 'Made in-house'), ('purchased_for_resale', 'Purchased for resale')], default='made_in_house', help_text='Whether this sellable product is made by the business or bought from a supplier for resale.', max_length=24)),
        migrations.RunPython(classify_non_production_products, migrations.RunPython.noop),
    ]
