# Generated by Django 5.2.17 on 2026-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alert_audio_chime_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpackprofile',
            name='name',
            field=models.CharField(help_text='Customer-facing option name, e.g. 2 L Bowl or Carton of 24.', max_length=100),
        ),
    ]
