# Generated by Django 5.2.17 on 2026-09-24 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_market_stock_tables(apps, schema_editor):
    """Create deferred cross-app tables without replacing existing data."""
    model_names = ("MarketStockLot", "DistributionReturn", "MarketStockMovement")
    with schema_editor.connection.cursor() as cursor:
        existing_tables = set(schema_editor.connection.introspection.table_names(cursor))

    for model_name in model_names:
        model = apps.get_model("inventory", model_name)
        if model._meta.db_table not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(model._meta.db_table)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_business_vertical'),
        ('inventory', '0010_alter_bulkpackprofile_name'),
        ('production', '0005_commerce_portion_commercial_snapshots'),
        ('sales', '0003_commerce_portion_commercial_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
            migrations.CreateModel(
                name='MarketStockLot',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('source', models.CharField(choices=[('production', 'Market-stock production'), ('return', 'Redistributable customer return')], max_length=12)),
                    ('received_date', models.DateField()),
                    ('expiry_date', models.DateField(blank=True, null=True)),
                    ('quantity_received', models.DecimalField(decimal_places=2, max_digits=14)),
                    ('quantity_available', models.DecimalField(decimal_places=2, max_digits=14)),
                    ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                    ('active', models.BooleanField(default=True)),
                    ('closed_reason', models.CharField(blank=True, default='', max_length=40)),
                    ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                    ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                    ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_stock_lots', to='inventory.finishedgood')),
                    ('production_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_stock_lots', to='production.productionbatch')),
                    ('source_sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_market_lots', to='sales.saleitem')),
                ],
                options={
                    'ordering': ['expiry_date', 'received_date', 'id'],
                },
            ),
            migrations.CreateModel(
                name='DistributionReturn',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('date', models.DateField()),
                    ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                    ('condition', models.CharField(choices=[('redistributable', 'Unsold and suitable for redistribution'), ('damaged', 'Damaged / unsellable')], max_length=20)),
                    ('reason', models.CharField(max_length=255)),
                    ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                    ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                    ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                    ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_returns', to='sales.saleitem')),
                    ('market_lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_return', to='inventory.marketstocklot')),
                ],
                options={
                    'ordering': ['-date', '-id'],
                },
            ),
            migrations.CreateModel(
                name='MarketStockMovement',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('updated_at', models.DateTimeField(auto_now=True)),
                    ('date', models.DateField()),
                    ('movement_type', models.CharField(choices=[('production_in', 'Production received into Market Stock'), ('release', 'Released to distributor'), ('return_in', 'Redistributable return received'), ('transfer_physical', 'Transferred to Physical Store'), ('expiry', 'Expired / unsellable write-off'), ('reversal', 'Production reversal')], max_length=24)),
                    ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                    ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                    ('unit_value', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                    ('note', models.CharField(blank=True, default='', max_length=255)),
                    ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.business')),
                    ('created_by', models.ForeignKey(blank=True, help_text='Person who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                    ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_stock_movements', to='sales.customer')),
                    ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.marketstocklot')),
                    ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_stock_movements', to='sales.sale')),
                ],
                options={
                    'ordering': ['-date', '-id'],
                },
            ),
            migrations.AddConstraint(
                model_name='marketstocklot',
                constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gte', 0)), name='market_lot_received_nonnegative'),
            ),
            migrations.AddConstraint(
                model_name='marketstocklot',
                constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='market_lot_available_nonnegative'),
            ),
            migrations.AddConstraint(
                model_name='marketstocklot',
                constraint=models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity_received'))), name='market_lot_available_not_above_received'),
            ),
            migrations.AddConstraint(
                model_name='marketstocklot',
                constraint=models.UniqueConstraint(condition=models.Q(('source', 'production')), fields=('production_batch',), name='one_market_production_lot_per_batch'),
            ),
            migrations.AddConstraint(
                model_name='distributionreturn',
                constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='distribution_return_quantity_positive'),
            ),
            ],
        ),
        migrations.RunPython(
            create_missing_market_stock_tables,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
