# Generated by Django 5.2.17 on 2026-10-06 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_portion_profile_show_public_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='variant_of',
            field=models.ForeignKey(blank=True, help_text='Optional parent product for a size or other variant. Each variant keeps its own recipe, stock and pricing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='inventory.finishedgood'),
        ),
    ]
