# Generated by Django 5.2.17 on 2026-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_finishedgood_description_finishedgood_variant_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgood',
            name='storefront_option_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='finishedgood',
            name='storefront_option_values',
            field=models.TextField(blank=True, default=''),
        ),
    ]
