import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0001_baseline"),
        ("accounts", "0004_audit_delivery_entitlements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                ("default_provider", models.CharField(choices=[("inhouse", "In-house fleet"), ("third_party", "External delivery provider"), ("hybrid", "Hybrid dispatch")], default="inhouse", max_length=16)),
                ("quote_valid_minutes", models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ("customer_tracking_enabled", models.BooleanField(default=True)),
                ("require_proof_of_delivery", models.BooleanField(default=False)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name_plural": "delivery settings"},
        ),
        migrations.AddConstraint(
            model_name="deliverysettings",
            constraint=models.UniqueConstraint(fields=("business",), name="one_delivery_settings_per_business"),
        ),
        migrations.CreateModel(
            name="DeliveryOrigin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("area", models.CharField(blank=True, default="", max_length=120)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-is_default", "name", "id"]},
        ),
        migrations.AddConstraint(
            model_name="deliveryorigin",
            constraint=models.UniqueConstraint(fields=("business", "name"), name="unique_delivery_origin_per_business"),
        ),
        migrations.CreateModel(
            name="DeliveryRateBand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("min_distance_km", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("max_distance_km", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("base_fee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("per_km_fee", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("minimum_order", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("eta_min_minutes", models.PositiveSmallIntegerField(default=20)),
                ("eta_max_minutes", models.PositiveSmallIntegerField(default=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["sort_order", "min_distance_km", "id"]},
        ),
        migrations.CreateModel(
            name="DeliveryArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(blank=True, default="", max_length=80)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("rate_band", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="areas", to="commerce.deliveryrateband")),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.AddConstraint(
            model_name="deliveryarea",
            constraint=models.UniqueConstraint(fields=("business", "name"), name="unique_delivery_area_per_business"),
        ),
        migrations.CreateModel(
            name="DeliveryDriver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("provider", models.CharField(choices=[("inhouse", "In-house"), ("third_party", "Third-party / courier")], default="inhouse", max_length=16)),
                ("vehicle_type", models.CharField(blank=True, default="", max_length=60)),
                ("vehicle_registration", models.CharField(blank=True, default="", max_length=60)),
                ("active", models.BooleanField(default=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="DeliveryQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("destination_address", models.CharField(max_length=255)),
                ("destination_latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("destination_longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=9)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=16)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, max_digits=16)),
                ("eta_min_minutes", models.PositiveSmallIntegerField(default=20)),
                ("eta_max_minutes", models.PositiveSmallIntegerField(default=60)),
                ("provider", models.CharField(choices=[("inhouse", "In-house fleet"), ("third_party", "External delivery provider"), ("hybrid", "Hybrid dispatch")], default="inhouse", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("active", "Active"), ("used", "Used"), ("expired", "Expired"), ("cancelled", "Cancelled")], default="active", max_length=12)),
                ("area", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="commerce.deliveryarea")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("origin", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="commerce.deliveryorigin")),
            ],
            options={"ordering": ["-created_at", "-id"], "indexes": [models.Index(fields=["business", "status", "expires_at"], name="delivery_quote_active_idx")]},
        ),
        migrations.AddField(
            model_name="commerceintake",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="commerceintake",
            name="delivery_quote",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="intakes", to="commerce.deliveryquote"),
        ),
        migrations.AddField(
            model_name="commercecheckoutsession",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="commercecheckoutsession",
            name="delivery_quote",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="checkouts", to="commerce.deliveryquote"),
        ),
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("provider", models.CharField(choices=[("inhouse", "In-house fleet"), ("third_party", "External delivery provider"), ("hybrid", "Hybrid dispatch")], default="inhouse", max_length=16)),
                ("external_reference", models.CharField(blank=True, default="", max_length=160)),
                ("external_tracking_url", models.URLField(blank=True, default="", max_length=500)),
                ("status", models.CharField(choices=[("pending", "Pending dispatch"), ("assigned", "Driver assigned"), ("ready", "Ready for pickup"), ("picked_up", "Picked up"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("failed", "Delivery failed"), ("returned", "Returned"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("status_note", models.CharField(blank=True, default="", max_length=255)),
                ("eta_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("proof_note", models.CharField(blank=True, default="", max_length=255)),
                ("proof_reference", models.CharField(blank=True, default="", max_length=255)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("driver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="commerce.deliverydriver")),
                ("intake", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="delivery_assignment", to="commerce.commerceintake")),
                ("origin", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="commerce.deliveryorigin")),
                ("quote", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="commerce.deliveryquote")),
            ],
            options={"ordering": ["-created_at", "-id"], "indexes": [models.Index(fields=["business", "status", "created_at"], name="delivery_assignment_idx")]},
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("pending", "Pending dispatch"), ("assigned", "Driver assigned"), ("ready", "Ready for pickup"), ("picked_up", "Picked up"), ("out_for_delivery", "Out for delivery"), ("delivered", "Delivered"), ("failed", "Delivery failed"), ("returned", "Returned"), ("cancelled", "Cancelled")], max_length=20)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("assignment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="commerce.deliveryassignment")),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(app_label)s_%(class)s_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
    ]
