# Generated by INPROFIC delivery provider plug-in implementation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_glovo_provider_accounts(apps, schema_editor):
    Business = apps.get_model("core", "Business")
    DeliveryProviderAccount = apps.get_model("commerce", "DeliveryProviderAccount")
    for business in Business.objects.all().only("id"):
        DeliveryProviderAccount.objects.get_or_create(
            business=business, name="Glovo",
            defaults={
                "provider_code": "glovo",
                "active": True,
                "sandbox": True,
                "auto_dispatch": False,
                "status_mapping": {
                    "created": "assigned",
                    "accepted": "assigned",
                    "ready_for_pickup": "ready",
                    "picked_up": "picked_up",
                    "courier_picked_up": "out_for_delivery",
                    "out_for_delivery": "out_for_delivery",
                    "delivered": "delivered",
                    "failed": "failed",
                    "cancelled": "cancelled",
                    "returned": "returned",
                },
            },
        )


def unseed_glovo_provider_accounts(apps, schema_editor):
    DeliveryProviderAccount = apps.get_model("commerce", "DeliveryProviderAccount")
    DeliveryProviderAccount.objects.filter(provider_code="glovo", name="Glovo", api_key="", api_secret="", order_endpoint="").delete()


class Migration(migrations.Migration):
    dependencies = [("commerce", "0002_delivery_system"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name="DeliveryProviderAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Glovo", max_length=100)),
                ("provider_code", models.CharField(choices=[("generic", "Generic courier / manual API"), ("glovo", "Glovo")], default="glovo", max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("sandbox", models.BooleanField(default=True)),
                ("auto_dispatch", models.BooleanField(default=False, help_text="When enabled, paid delivery checkouts are pushed to this provider automatically.")),
                ("base_url", models.URLField(blank=True, default="", help_text="Provider API base URL from the delivery provider portal.", max_length=255)),
                ("quote_endpoint", models.CharField(blank=True, default="", help_text="Optional relative/absolute quote endpoint. Leave blank to use INPROFIC rate bands.", max_length=160)),
                ("order_endpoint", models.CharField(blank=True, default="", help_text="Relative/absolute endpoint used to create a delivery job.", max_length=160)),
                ("cancel_endpoint", models.CharField(blank=True, default="", help_text="Optional endpoint template for cancellation; {external_reference} is replaced when present.", max_length=160)),
                ("api_key", models.CharField(blank=True, default="", max_length=255)),
                ("api_secret", models.CharField(blank=True, default="", max_length=255)),
                ("store_id", models.CharField(blank=True, default="", help_text="Glovo/partner store identifier when required by the provider.", max_length=120)),
                ("webhook_secret", models.CharField(blank=True, default="", max_length=255)),
                ("tracking_base_url", models.URLField(blank=True, default="", max_length=255)),
                ("status_mapping", models.JSONField(blank=True, default=dict, help_text="Map provider statuses to INPROFIC statuses. Example: {\"delivered\": \"delivered\"}.")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="commerce_deliveryprovideraccount_set", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, help_text="Person who created this record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commerce_deliveryprovideraccount_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["provider_code", "name", "id"], "constraints": [models.UniqueConstraint(fields=("business", "name"), name="unique_delivery_provider_account_per_business")]},
        ),
        migrations.AddField("DeliverySettings", "default_provider_account", models.ForeignKey(blank=True, help_text="Optional configured plug-in provider account, such as Glovo. Leave blank for in-house/manual dispatch.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="default_for_settings", to="commerce.deliveryprovideraccount")),
        migrations.AddField("DeliveryQuote", "provider_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="quotes", to="commerce.deliveryprovideraccount")),
        migrations.AddField("DeliveryQuote", "provider_quote_reference", models.CharField(blank=True, default="", max_length=160)),
        migrations.AddField("DeliveryQuote", "provider_payload", models.JSONField(blank=True, default=dict)),
        migrations.AddField("DeliveryAssignment", "provider_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assignments", to="commerce.deliveryprovideraccount")),
        migrations.AddField("DeliveryAssignment", "provider_order_id", models.CharField(blank=True, default="", max_length=160)),
        migrations.AddField("DeliveryAssignment", "provider_status", models.CharField(blank=True, default="", max_length=80)),
        migrations.AddField("DeliveryAssignment", "provider_payload", models.JSONField(blank=True, default=dict)),
        migrations.RunPython(seed_glovo_provider_accounts, unseed_glovo_provider_accounts),
    ]
