# Generated by Django 5.2.17 on 2026-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_alert_audio_chime_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercesettings',
            name='notification_sound_enabled',
            field=models.BooleanField(default=True, help_text='Play an alert sound while unread Commerce activity needs attention.'),
        ),
    ]
