# Generated by Django 5.2.17 on 2026-10-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_delivery_ready_notification_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercesettings',
            name='basket_dock_heading',
            field=models.CharField(blank=True, default='Review quantities and checkout', max_length=100),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='basket_dock_subheading',
            field=models.CharField(blank=True, default='Your basket', max_length=180),
        ),
    ]
