# Generated by Django 5.2.17 on 2026-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_commercesettings_basket_dock_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecheckoutitem',
            name='product_option_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='commercecheckoutitem',
            name='product_option_value',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='commerceintakeitem',
            name='product_option_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='commerceintakeitem',
            name='product_option_value',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
