# Generated by Django 5.2.17 on 2026-10-07 20:26

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_commercecheckoutitem_product_option_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercecheckoutitem',
            name='preorder_lead_time',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='commercecheckoutsession',
            name='customer_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='commerceintake',
            name='customer_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='commerceintakeitem',
            name='preorder_lead_time',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='receipt_contact_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='receipt_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='receipt_contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='receipt_contact_website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='receipt_logo',
            field=models.ImageField(blank=True, upload_to=commerce.models.commerce_receipt_logo_upload_to),
        ),
        migrations.AddField(
            model_name='commercesettings',
            name='receipt_tagline',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
