# Generated by Django 5.2.18 on 2026-10-09 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_deliveryassignment_manual_rider_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='manual_rider_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='manual_rider_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='manual_rider_vehicle',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='commerce.deliverydriver'),
        ),
    ]
