# Generated by Django 5.2.18 on 2026-10-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_deliverybatch_independent_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryarea',
            name='car_rate_band',
            field=models.ForeignKey(blank=True, help_text='Price band used when a customer chooses car delivery to this destination.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car_areas', to='commerce.deliveryrateband'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='vehicle_mode',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], default='motorbike', max_length=12),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='vehicle_mode',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], default='motorbike', max_length=12),
        ),
        migrations.AddField(
            model_name='deliverydriver',
            name='vehicle_mode',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], default='motorbike', max_length=12),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='vehicle_mode',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], default='motorbike', max_length=12),
        ),
        migrations.AddField(
            model_name='deliveryrateband',
            name='vehicle_mode',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car')], default='motorbike', max_length=12),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='car_enabled',
            field=models.BooleanField(default=False, help_text='Also offer delivery by car. Customers then choose Motorbike or Car at checkout, each at its own price band.'),
        ),
    ]
