# Generated by Django 5.2.18 on 2026-10-10 08:12

from django.db import migrations, models


def enable_car_delivery(apps, schema_editor):
    """0032 created every row with car delivery off. Car now appears at checkout wherever an active Car price
    band applies, so switch existing rows on: with no Car band configured nothing changes for customers."""
    apps.get_model("commerce", "DeliverySettings")._base_manager.update(car_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_delivery_vehicle_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysettings',
            name='car_enabled',
            field=models.BooleanField(default=True, help_text='Car delivery is offered at checkout wherever an active Car price band applies. Untick to pause car delivery without deleting its price bands.'),
        ),
        migrations.RunPython(enable_car_delivery, migrations.RunPython.noop),
    ]
