from django.urls import path
from . import views
from . import finance_views as finance
from . import operations
from . import pwa
from . import audit_views
from expenses import views as expense_views

urlpatterns = [
    path("manifest.webmanifest", pwa.manifest, name="pwa_manifest"),
    path("pwa/manifest/<slug:business_slug>.webmanifest", pwa.tenant_manifest, name="pwa_manifest_tenant"),
    path("service-worker.js", pwa.service_worker, name="pwa_service_worker"),
    path("pwa/offline/", pwa.offline, name="pwa_offline"),
    path("pwa/launch/<slug:business_slug>/", pwa.launch, name="pwa_launch"),
    path("health/", operations.health, name="health"),
    path("ops/run-jobs/", operations.run_jobs, name="run_jobs"),
    path("ops/dispatch-web-push/", operations.dispatch_web_push, name="dispatch_web_push"),
    path("", views.marketing_home, name="marketing_home"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/tour/complete/", views.onboarding_tour_complete, name="onboarding_tour_complete"),
    path("audit/", audit_views.audit_workspace, name="audit_workspace"),
    path("audit/query/", audit_views.audit_query_create, name="audit_query_create"),
    path("audit/query/<int:pk>/update/", audit_views.audit_query_update, name="audit_query_update"),
    path("audit/export.xlsx", audit_views.audit_export_xlsx, name="audit_export_xlsx"),
    path("dashboard/financial-breakdown/", views.dashboard_financial_breakdown, name="dashboard_financial_breakdown"),
    path("business/settings/", views.business_settings, name="business_settings"),
    path("business/switch/", views.switch_business, name="switch_business"),
    path("search/", views.dashboard_search, name="dashboard_search"),
    path("search/detail/", views.dashboard_search_detail, name="dashboard_search_detail"),
    path("reports/", views.reports, name="reports"),
    path("reports/export/stock.csv", views.export_stock_csv, name="export_stock_csv"),
    path("reports/export/procurement.csv", views.export_procurement_csv, name="export_procurement_csv"),
    path("reports/export/production.csv", views.export_production_csv, name="export_production_csv"),
    path("reports/export/sales.csv", views.export_sales_csv, name="export_sales_csv"),
    path("reports/backup.json", views.backup_json, name="backup_json"),
    path("reports/export/stock.xlsx", views.export_stock_xlsx, name="export_stock_xlsx"),
    path("reports/export/market-stock.csv", views.export_market_stock_csv, name="export_market_stock_csv"),
    path("reports/export/market-stock.xlsx", views.export_market_stock_xlsx, name="export_market_stock_xlsx"),
    path("reports/export/procurement.xlsx", views.export_procurement_xlsx, name="export_procurement_xlsx"),
    path("reports/export/production.xlsx", views.export_production_xlsx, name="export_production_xlsx"),
    path("reports/export/sales.xlsx", views.export_sales_xlsx, name="export_sales_xlsx"),
    path("reports/export/expenses.csv", views.export_expenses_csv, name="export_expenses_csv"),
    path("reports/export/expenses.xlsx", views.export_expenses_xlsx, name="export_expenses_xlsx"),
    path("reports/export/adjustments.csv", views.export_adjustments_csv, name="export_adjustments_csv"),
    path("reports/export/adjustments.xlsx", views.export_adjustments_xlsx, name="export_adjustments_xlsx"),
    path("reports/export/operational-dispenses.csv", views.export_operational_dispenses_csv, name="export_operational_dispenses_csv"),
    path("reports/export/operational-dispenses.xlsx", views.export_operational_dispenses_xlsx, name="export_operational_dispenses_xlsx"),
    path("reports/export/financial.csv", views.export_financial_csv, name="export_financial_csv"),
    path("reports/export/financial.xlsx", views.export_financial_xlsx, name="export_financial_xlsx"),
    path("finance/", finance.finance_dashboard, name="finance_dashboard"),
    path("finance/export/money-movements.csv", finance.export_money_movements_csv, name="finance_money_movements_csv"),
    path("finance/export/money-movements.xlsx", finance.export_money_movements_xlsx, name="finance_money_movements_xlsx"),
    path("finance/export/audit-trail.csv", finance.export_audit_trail_csv, name="finance_audit_trail_csv"),
    path("finance/export/audit-trail.xlsx", finance.export_audit_trail_xlsx, name="finance_audit_trail_xlsx"),
    path("finance/accounts/add/", finance.cash_account_form, name="cash_account_add"),
    path("finance/accounts/<int:pk>/edit/", finance.cash_account_form, name="cash_account_edit"),
    path("finance/accounts/<int:pk>/delete/", finance.cash_account_delete, name="cash_account_delete"),
    path("finance/supplier-payment/add/", finance.supplier_payment_form, name="supplier_payment_add"),
    path("finance/customer-payment/add/", finance.customer_payment_form, name="customer_payment_add"),
    path("finance/stock-adjustment/add/", finance.stock_adjustment_form, name="stock_adjustment_add"),
    path("finance/expense-payment/add/", expense_views.expense_payment_form, name="expense_payment_add"),
]
